language: python
sudo: false

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - libgsl0-dev
      - libgsl0ldbl
      - gfortran
     # - gunzip

env:
    global:
        - DEPENDS="cython numpy scipy"
        - DEPENDS_CONDA='dipy nibabel'
        - DEPENDS_PIP="cythongsl"

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - python: 2.7
      env:
        - DEPENDS="nomkl numpy==1.10.4 cython==0.21"
        - DEPENDS_CONDA='nibabel==2.0.1 dipy==0.11"
        - DEPENDS_PIP="cythongsl==0.2.1 scipy==0.14"
    - python: 3.4
      env:
        - DEPENDS="nomkl numpy==1.10.4 cython==0.21"
        - DEPENDS_CONDA='nibabel==2.0.1 dipy==0.11"
        - DEPENDS_PIP="cythongsl==0.2.1 scipy==0.14"
        
notifications:
    email: false

before_install:
    # no py36 conda build for dipy yet
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then DEPENDS_CONDA='nibabel' DEPENDS_PIP="cythongsl dipy"; fi;
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $DEPENDS pip
    - source activate test-environment
    - python --version # just to check
    - pip install nose coverage coveralls
    - source deactivate
    - source activate test-environment

install:
    - conda config --add channels conda-forge
    - conda install $DEPENDS_CONDA
    - pip install $DEPENDS_PIP
    - python setup.py build_ext -i
    - python setup.py install

before_script:
    - mkdir $HOME/.python-eggs
    - chmod og-w $HOME/.python-eggs

script:
    - mkdir tester
    - cd tester
    - nosetests --verbose --exe --with-coverage --cover-package=nlsam ../nlsam/tests/
    - bash ../nlsam/tests/test_scripts.sh

#after_success:
#    - coveralls
